/**
 * Tool capability tags — what a tool can DO, as opposed to what it is about
 * (`TOOL_DOMAINS`). Prism's permission rules match on these: one
 * `capability:network` rule covers every tool that reaches the network,
 * including ones added after the rule was written.
 *
 * The vocabulary is shared with prism-service
 * (`src/services/permissions/types.ts` `CAPABILITIES`); keep the two lists
 * identical.
 *
 *   fs_read               reads the sandboxed workspace (or a path the caller names)
 *   fs_write              creates, edits, moves or deletes files
 *   shell                 runs a process, or inspects/kills one it started
 *   network               leaves the host: HTTP, DNS, third-party APIs
 *   mcp                   reserved for MCP tools (prism assigns it)
 *   subagent              reserved for delegation tools (prism assigns it)
 *   memory_write          persists agent memory or datastore records
 *   external_side_effect  changes the world outside the workspace: sends a
 *                         message, flips a light, schedules a job, drives a browser
 *
 * An empty list is a real answer: the tool is pure computation over its
 * arguments (unit conversion, hashing, a static dataset lookup).
 *
 * Every tool needs an entry — `validateToolRegistries()` reports a missing or
 * stale one and `RegistryIntegrity.test.ts` fails on it — so a new tool's
 * author has to decide, rather than inherit a default.
 */

export const TOOL_CAPABILITY_TAGS = [
  "fs_read",
  "fs_write",
  "shell",
  "network",
  "mcp",
  "subagent",
  "memory_write",
  "external_side_effect",
] as const;

export type ToolCapabilityTag = (typeof TOOL_CAPABILITY_TAGS)[number];

export const TOOL_CAPABILITIES: Record<string, readonly ToolCapabilityTag[]> = {
  // ── Weather & Environment ──
  get_weather_forecast: ["network"],
  get_canada_avalanche_forecast: ["network"],
  get_weather: ["network"],
  get_local_environment: ["network"],
  get_earthquakes: ["network"],
  get_solar_activity: ["network"],
  get_aurora_forecast: ["network"],
  get_solar_wind: ["network"],
  get_twilight: ["network"],
  get_tides: ["network"],
  get_wildfires: ["network"],
  get_iss_location: ["network"],
  get_near_earth_objects: ["network"],
  get_space_launches: ["network"],
  get_nasa_apod: ["network"],
  get_moon_phase: ["network"],
  get_canada_weather_warnings: ["network"],
  get_detailed_air_quality: ["network"],
  get_satellite_imagery: ["network"],
  // ── Health ──
  get_pollen_forecast: ["network"],
  search_drugs: ["network"],
  get_drug_adverse_events: ["network"],
  get_drug_recalls: ["network"],
  search_gym_exercises: [],
  get_gym_exercise_categories: [],
  get_gym_exercise_by_id: [],
  search_food_nutrition: [],
  rank_foods_by_nutrient: [],
  compare_food_nutrition: [],
  get_nutrition_reference: [],
  get_nutritional_requirements: [],
  calculate_caloric_needs: [],
  analyze_nutrient_gaps: [],
  search_food_substitutes: [],
  estimate_exercise_calories: [],
  calculate_hydration_needs: [],
  build_meal_plan: [],
  check_drug_nutrient_interactions: [],
  list_drug_dosage_forms: [],
  // ── Knowledge ──
  read_rss_feed: ["network"],
  get_pypi_package: ["network"],
  search_books: ["network"],
  search_library_docs: ["network"],
  get_country: ["network"],
  get_element: [],
  get_exoplanet: [],
  get_anime: ["network"],
  get_word_definition: ["network"],
  search_papers: ["network"],
  search_youtube: ["network"],
  get_youtube_video: ["network"],
  download_video: ["network"],
  trim_video: ["network"],
  get_package_info: ["network"],
  get_wikipedia_summary: ["network"],
  get_on_this_day: ["network"],
  list_development_indicators: [],
  get_music: ["network"],
  get_wayback_snapshot: ["network"],
  get_stackoverflow_questions: ["network"],
  search_patents: ["network"],
  search_craigslist: ["network"],
  search_kijiji: ["network"],
  search_autotrader: ["network"],
  search_spotify: ["network"],
  get_spotify: ["network"],
  control_spotify: ["network", "external_side_effect"],
  // ── Events ──
  get_events: ["network"],
  // ── Markets & Commodities ──
  get_commodities: ["network"],
  // ── Trends ──
  get_trends: ["network"],
  get_github_trending: ["network"],
  // ── Products ──
  search_products: ["network"],
  get_trending_products: ["network"],
  get_watchlist_availability: ["network"],
  check_sku_availability: ["network"],
  get_costco_us_products: ["network"],
  get_costco_ca_products: ["network"],
  search_amazon_products: ["network"],
  search_ebay: ["network"],
  search_etsy: ["network"],
  // ── Finance ──
  get_market_news: ["network"],
  get_earnings_calendar: ["network"],
  get_stock: ["network"],
  get_macro: ["network"],
  get_historical_prices: ["network"],
  get_technical_analysis: ["network"],
  get_volatility: ["network"],
  get_fear_greed_index: ["network"],
  get_sec_filings: ["network"],
  get_sector_performance: ["network"],
  // ── Core Harness Tools ──
  read_url: ["network"],
  execute_python: ["shell", "fs_write", "network"],
  evaluate_expression: [],
  execute_javascript: ["shell", "network"],
  search_web: ["network"],
  save_memory: ["memory_write"],
  think: [],
  sleep: [],
  emit_structured_output: [],
  write_datastore: ["memory_write"],
  query_datastore: [],
  delete_datastore: ["memory_write"],
  // ── Reddit ──
  search_reddit: ["network"],
  search_reddit_subreddits: ["network"],
  get_reddit_subreddit_info: ["network"],
  get_reddit_subreddit_feed: ["network"],
  get_reddit_subreddit_rules: ["network"],
  get_reddit_subreddit_wiki_pages: ["network"],
  get_reddit_subreddit_wiki_page: ["network"],
  get_reddit_user_history: ["network"],
  get_reddit_user_profile: ["network"],
  // ── Movies & TV ──
  search_media: ["network"],
  get_media_details: ["network"],
  get_media_credits: ["network"],
  get_trending_media: ["network"],
  browse_media: ["network"],
  get_media_genres: ["network"],
  get_now_playing_media: ["network"],
  get_media_recommendations: ["network"],
  search_person: ["network"],
  get_watch_providers: ["network"],
  // ── Transit ──
  get_translink_next_bus: ["network"],
  get_translink_stop_info: ["network"],
  search_translink_stops_nearby: ["network"],
  get_translink_route_info: ["network"],
  get_flight_status: ["network"],
  // ── Compute ──
  execute_shell: ["shell", "fs_write", "network"],
  convert_units: [],
  parse_datetime: [],
  transform_json: [],
  generate_csv: [],
  render_latex: [],
  generate_diagram: [],
  diff_text: [],
  generate_hash: [],
  test_regex: [],
  convert_encoding: [],
  convert_video_to_gif: ["fs_read", "network"],
  parse_cron_expression: [],
  analyze_csv: [],
  compare_json: [],
  validate_json_schema: [],
  // ── Creative ──
  generate_qr_code: [],
  scan_barcode: ["fs_read", "network"],
  render_code: [],
  generate_avatar: [],
  generate_ascii_banner: [],
  convert_color: [],
  manipulate_image: ["fs_read", "network"],
  convert_image_to_ascii: ["fs_read", "network"],
  draw_turtle_graphics: [],
  create_3d_mesh: [],
  create_3d_voxel: [],
  create_3d_scene: [],
  get_emoji_combination: ["network"],
  get_emoji_combinations: ["network"],
  generate_image: ["network"],
  describe_image: ["network"],
  detect_objects: ["network"],
  remove_background: ["network"],
  synthesize_speech: ["network"],
  synthesize_speech_local: [],
  create_vector_animation: [],
  generate_audio: [],
  remix_audio: ["fs_read", "network"],
  transcribe_audio: ["network"],
  // ── Utilities ──
  convert_currency: ["network"],
  get_time_in_timezone: ["network"],
  get_ip_info: ["network"],
  search_nearby_places: ["network"],
  search_places: ["network"],
  generate_map: ["network"],
  generate_chart: [],
  search_airports: [],
  get_public_webcams: ["network"],
  // ── Maritime ──
  get_tracked_vessels: ["network"],
  get_vessel_by_mmsi: ["network"],
  search_vessels: ["network"],
  get_vessels_in_area: ["network"],
  get_ais_messages: ["network"],
  // ── Energy ──
  get_energy_indicators: ["network"],
  get_energy_catalog: ["network"],
  get_energy_facets: ["network"],
  search_energy: ["network"],
  get_electricity_retail_sales: ["network"],
  get_petroleum_prices: ["network"],
  get_natural_gas_prices: ["network"],
  // ── Core Workspace Tools ──
  read_file: ["fs_read"],
  write_file: ["fs_write"],
  replace_in_file: ["fs_write"],
  apply_patch: ["fs_write"],
  list_directory: ["fs_read"],
  search_file_contents: ["fs_read"],
  find_files: ["fs_read"],
  read_files: ["fs_read"],
  get_file_info: ["fs_read"],
  move_file: ["fs_write"],
  delete_file: ["fs_write"],
  execute_command: ["shell", "fs_write", "network"],
  get_background_output: ["shell"],
  list_background_processes: ["shell"],
  kill_process: ["shell"],
  summarize_project: ["fs_read"],
  run_git: ["fs_read"],
  code_intel: ["fs_read", "fs_write"],
  debug: ["shell", "fs_read"],
  commit_split: ["fs_write"],
  edit_notebook: ["fs_write"],
  // ── Web ──
  read_web_page: ["network"],
  read_image_text: ["fs_read", "network"],
  read_pdf: ["network"],
  read_docx: ["network"],
  read_csv: ["fs_read", "network"],
  read_spreadsheet: ["network"],
  search_news: ["network"],
  search_images: ["network"],
  search_videos: ["network"],
  // ── Browser ──
  control_browser: ["network", "external_side_effect"],
  execute_browser_script: ["network", "external_side_effect"],
  // ── Core Task Tools ──
  create_task: [],
  list_tasks: [],
  get_task: [],
  update_task: [],
  // ── Communication ──
  send_email: ["network", "external_side_effect"],
  search_email: ["network"],
  read_email: ["network"],
  send_sms: ["network", "external_side_effect"],
  list_sms_messages: ["network"],
  get_sms_account: ["network"],
  lookup_phone_number: ["network"],
  list_phone_numbers: ["network"],
  send_push_notification: ["network", "external_side_effect"],
  send_webhook: ["network", "external_side_effect"],
  // ── Discord ──
  search_discord_messages: ["network"],
  get_discord_message_analytics: ["network"],
  get_discord_server_activity: ["network"],
  get_discord_guild_channels: ["network"],
  get_discord_guild_members: ["network"],
  get_discord_guild_emojis: ["network"],
  get_bot_stats: ["network"],
  get_bot_guilds: ["network"],
  get_bot_activity_timeline: ["network"],
  get_discord_user_heatmap_data: ["network"],
  get_discord_mention_leaderboard: ["network"],
  get_discord_message_leaderboard: ["network"],
  get_discord_word_frequencies: ["network"],
  react_to_discord_message: ["network", "external_side_effect"],
  get_discord_voice_channel_members: ["network"],
  get_discord_user_profile: ["network"],
  get_discord_channel_activity_stats: ["network"],
  get_discord_gold_balance: ["network"],
  give_discord_gold: ["network", "external_side_effect"],
  mug_discord_gold: ["network", "external_side_effect"],
  // ── Smart Home ──
  list_lights: ["network"],
  set_light_state: ["network", "external_side_effect"],
  toggle_light_power: ["network", "external_side_effect"],
  start_light_breathe_effect: ["network", "external_side_effect"],
  start_light_pulse_effect: ["network", "external_side_effect"],
  stop_light_effects: ["network", "external_side_effect"],
  list_light_scenes: ["network"],
  activate_light_scene: ["network", "external_side_effect"],
  start_light_move_effect: ["network", "external_side_effect"],
  start_light_flame_effect: ["network", "external_side_effect"],
  start_light_morph_effect: ["network", "external_side_effect"],
  set_light_states: ["network", "external_side_effect"],
  paint_lights_from_image: ["fs_read", "network", "external_side_effect"],
  adjust_light_state: ["network", "external_side_effect"],
  enable_light_night_lock: ["network", "external_side_effect"],
  get_light_health: ["network"],
  // ── Agent Management ──
  create_custom_agent: ["network", "external_side_effect"],
  list_custom_agents: ["network"],
  list_agents: ["network"],
  update_custom_agent: ["network", "external_side_effect"],
  // ── Core Discover Tools ──
  search_tools: [],
  // ── Core Schedule Tools ──
  create_cron_job: ["external_side_effect"],
  list_cron_jobs: [],
  delete_cron_job: ["external_side_effect"],
  trigger_cron_job: ["external_side_effect"],
  // ── Gaming ──
  get_dota: ["network"],
  get_steam_profile: ["network"],
  create_bonfire: [],
  // ── Torrent ──
  search_torrents: ["network"],
  download_torrent: ["network", "external_side_effect"],
  get_torrent_status: ["network"],
  // ── Network Intelligence ──
  dns_lookup: ["network"],
  whois_lookup: ["network"],
  ssl_certificate_check: ["network"],
  port_scan: ["network", "external_side_effect"],
  http_headers: ["network"],
  ping_host: ["network"],
  // ── Security ──
  check_breach: ["network"],
  // ── Calendar ──
  get_calendar_events: ["network"],
  create_calendar_event: ["network", "external_side_effect"],
  get_free_busy: ["network"],
  // ── Infrastructure ──
  get_infrastructure_status: ["network"],
  get_container_diagnostics: ["network"],
  get_container_logs: ["network"],
  // ── Analytics ──
  get_web_analytics: ["network"],
};
